apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "binay.sinha53@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
